In [1]:
import numpy as np, pandas as pd
import json
import ast 
from textblob import TextBlob
import nltk
import torch
import pickle
from scipy import spatial
import warnings
warnings.filterwarnings('ignore')
import spacy
from nltk import Tree
en_nlp = spacy.load('en')
from nltk.stem.lancaster import LancasterStemmer
st = LancasterStemmer()
from sklearn.feature_extraction.text import TfidfVectorizer, TfidfTransformer

In [31]:
# !conda update pandas --y

In [4]:
# comment out to avoid overwriting original data
# load train data
train = pd.read_csv("data/train.csv")

In [5]:
train.shape

(1314, 4)

### Loading Embedding dictionary

In [45]:
with open("data/dict_embeddings3.pickle", "rb") as f:
    d1 = pickle.load(f)

with open("data/dict_embeddings4.pickle", "rb") as f:
    d2 = pickle.load(f)

In [46]:
# key - sentence / question , val - vector
dict_emb = dict(d1)
dict_emb.update(d2)

In [47]:
dict_emb['To whom did the Virgin Mary allegedly appear in 1858 in Lourdes France?'][0]

array([ 0.00746889,  0.02421027,  0.07833809, ...,  0.04228063,
        0.06608193, -0.00488943], dtype=float32)

In [49]:
len(dict_emb)

4823

In [50]:
del d1, d2

## Data Processing

In [51]:
# find the index of the sentence that contains answer
def get_target(x):
    idx = -1
    for i in range(len(x["sentences"])):
        if x["text"] in x["sentences"][i]: idx = i
    return idx

In [52]:
train.head(3)

context  \
0  Architecturally, the school has a Catholic cha...   
1  Architecturally, the school has a Catholic cha...   
2  Architecturally, the school has a Catholic cha...   

                                            question  answer_start  \
0  To whom did the Virgin Mary allegedly appear i...           515   
1  What is in front of the Notre Dame Main Building?           188   
2  The Basilica of the Sacred heart at Notre Dame...           279   

                         text  \
0  Saint Bernadette Soubirous   
1   a copper statue of Christ   
2           the Main Building   

                                           sentences  target  \
0  [Architecturally, the school has a Catholic ch...       5   
1  [Architecturally, the school has a Catholic ch...       2   
2  [Architecturally, the school has a Catholic ch...       3   

                                            sent_emb  \
0  [[-0.00991958, -0.035521798, 0.06675484, -0.02...   
1  [[-0.00991958, -0.035521798, 0.06675484, -0.02...   
2  [[-0.00991958, -0.035521798, 0.06675484, -0.02...   

                                           quest_emb  \
0  [[-0.0058745374, -0.07653264, 0.08423636, -0.0...   
1  [[0.017040426, -0.06193916, 0.07699205, -0.010...   
2  [[0.013891986, -0.051962323, 0.069856785, -0.0...   

                                          cosine_sim  \
0  [0.25390303134918213, 0.22334301471710205, 0.2...   
1  [0.2634468674659729, 0.2264377474784851, 0.219...   
2  [0.24388277530670166, 0.2215394377708435, 0.22...   

                                       euclidean_dis  \
0  [1.7075382, 1.7290226, 1.8517298, 1.4138652, 1...   
1  [2.1715844, 2.0053604, 1.9923788, 1.6267016, 2...   
2  [2.072908, 1.9996178, 2.110013, 1.616806, 1.98...   

                                      euclidean_dis2  \
0  [1.3067281246185303, 1.3149230480194092, 1.360...   
1  [1.4736297130584717, 1.416107416152954, 1.4115...   
2  [1.4397597312927246, 1.4140784740447998, 1.452...   

                                       minkowski_dis  \
0  [60.20494, 61.16893, 64.51268, 56.288124, 57.5...   
1  [68.16332, 66.02714, 65.82747, 58.949272, 67.1...   
2  [66.24587, 65.72272, 67.814575, 58.87599, 64.8...   

                                       chebyshev_dis  pred_idx_cos  \
0  [0.1423744, 0.10892366, 0.14755285, 0.09070109...             5   
1  [0.11970146, 0.118082315, 0.12687306, 0.134611...             3   
2  [0.12093631, 0.12933947, 0.13097605, 0.1125107...             3   

   pred_idx_euc  pred_idx_min  pred_idx_che  
0             5             5             3  
1             3             3             1  
2             3             3             4

In [53]:
train.shape

(1314, 17)

In [54]:
train.dropna(inplace=True)

In [55]:
train.shape

(1314, 17)

In [56]:
dict_emb['Architecturally, the school has a Catholic character.']

array([[ 0.00746889, -0.05086312,  0.00736477, ...,  0.04118384,
         0.01421824, -0.0138564 ]], dtype=float32)

In [57]:
def process_data(train):
    
    print("step 1")
    train['sentences'] = train['context'].apply(lambda x: [item.raw for item in TextBlob(x).sentences])
    
    print("step 2")
    train["target"] = train.apply(get_target, axis = 1)
    
    print("step 3")
    train['sent_emb'] = train['sentences'].apply(lambda x: [dict_emb[item][0] if item in\
                                                           dict_emb else np.zeros(4096) for item in x])
    print("step 4")
    train['quest_emb'] = train['question'].apply(lambda x: dict_emb[x] if x in dict_emb else np.zeros(4096) )
        
    return train   

In [58]:
train = process_data(train)

step 1
step 2
step 3
step 4


In [59]:
train.head(3)

context  \
0  Architecturally, the school has a Catholic cha...   
1  Architecturally, the school has a Catholic cha...   
2  Architecturally, the school has a Catholic cha...   

                                            question  answer_start  \
0  To whom did the Virgin Mary allegedly appear i...           515   
1  What is in front of the Notre Dame Main Building?           188   
2  The Basilica of the Sacred heart at Notre Dame...           279   

                         text  \
0  Saint Bernadette Soubirous   
1   a copper statue of Christ   
2           the Main Building   

                                           sentences  target  \
0  [Architecturally, the school has a Catholic ch...       5   
1  [Architecturally, the school has a Catholic ch...       2   
2  [Architecturally, the school has a Catholic ch...       3   

                                            sent_emb  \
0  [[0.007468889, -0.050863117, 0.0073647713, -0....   
1  [[0.007468889, -0.050863117, 0.0073647713, -0....   
2  [[0.007468889, -0.050863117, 0.0073647713, -0....   

                                           quest_emb  \
0  [[0.007468889, 0.024210269, 0.07833809, -0.017...   
1  [[0.10951651, 0.11030624, 0.05210008, 0.030539...   
2  [[0.007468889, -0.028770322, 0.13643634, -0.00...   

                                          cosine_sim  \
0  [0.25390303134918213, 0.22334301471710205, 0.2...   
1  [0.2634468674659729, 0.2264377474784851, 0.219...   
2  [0.24388277530670166, 0.2215394377708435, 0.22...   

                                       euclidean_dis  \
0  [1.7075382, 1.7290226, 1.8517298, 1.4138652, 1...   
1  [2.1715844, 2.0053604, 1.9923788, 1.6267016, 2...   
2  [2.072908, 1.9996178, 2.110013, 1.616806, 1.98...   

                                      euclidean_dis2  \
0  [1.3067281246185303, 1.3149230480194092, 1.360...   
1  [1.4736297130584717, 1.416107416152954, 1.4115...   
2  [1.4397597312927246, 1.4140784740447998, 1.452...   

                                       minkowski_dis  \
0  [60.20494, 61.16893, 64.51268, 56.288124, 57.5...   
1  [68.16332, 66.02714, 65.82747, 58.949272, 67.1...   
2  [66.24587, 65.72272, 67.814575, 58.87599, 64.8...   

                                       chebyshev_dis  pred_idx_cos  \
0  [0.1423744, 0.10892366, 0.14755285, 0.09070109...             5   
1  [0.11970146, 0.118082315, 0.12687306, 0.134611...             3   
2  [0.12093631, 0.12933947, 0.13097605, 0.1125107...             3   

   pred_idx_euc  pred_idx_min  pred_idx_che  
0             5             5             3  
1             3             3             1  
2             3             3             4

In [60]:
train.iloc[0,:]['sent_emb']

[array([ 0.00746889, -0.05086312,  0.00736477, ...,  0.04118384,
         0.01421824, -0.0138564 ], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.00746889, 0.00995224, 0.19095322, ..., 0.00119954, 0.04134529,
        0.03366186], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([ 0.00746889, -0.05682991,  0.11969507, ..., -0.01752904,
         0.01482137, -0.00012652], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([ 0.00746889, -0.01367913,  0.1417282 , ...,  0.0098886 ,
        -0.00070966,  0.06526422], dtype=float32)]

## Predicted Cosine & Euclidean & other Index

In [61]:
def cosine_sim(x):
    li = []
    for item in x["sent_emb"]:
        li.append(spatial.distance.cosine(item,x["quest_emb"][0]))
    return li   

In [62]:
def euc_dist(x):
    li = []
    for item in x["sent_emb"]:
#         print(item)
#         print(x["quest_emb"][0])
#         print()
        li.append(spatial.distance.euclidean(item,x["quest_emb"][0]))
    return li   

In [63]:
# actually manhatten distance as p = 1
def min_dist(x,p=1):
    li = []
    for item in x["sent_emb"]:
#         print(item)
#         print(x["quest_emb"][0])
#         print()
        li.append(spatial.distance.minkowski(item,x["quest_emb"][0],p))
    return li  

In [64]:
def che_dist(x):
    li = []
    for item in x["sent_emb"]:
#         print(item)
#         print(x["quest_emb"][0])
#         print()
        li.append(spatial.distance.chebyshev(item,x["quest_emb"][0]))
    return li  

In [65]:
def pred_idx(distances):
    return np.argmin(distances)   

In [66]:
def predictions(train):
    
    train["cosine_sim"] = train.apply(cosine_sim, axis = 1)
    train["diff"] = (train["quest_emb"] - train["sent_emb"])**2
    train["euclidean_dis"] = train["diff"].apply(lambda x: list(np.sum(x, axis = 1)))
    train["euclidean_dis2"]= train.apply(euc_dist,axis = 1)
    train["minkowski_dis"] = train.apply(min_dist,axis = 1)
    train["chebyshev_dis"] = train.apply(che_dist,axis = 1)
    del train["diff"]
    
    print("cosine start")
    
    train["pred_idx_cos"] = train["cosine_sim"].apply(lambda x: pred_idx(x))
    train["pred_idx_euc"] = train["euclidean_dis"].apply(lambda x: pred_idx(x))
    train["pred_idx_min"] = train["minkowski_dis"].apply(lambda x: pred_idx(x))
    train["pred_idx_che"] = train["chebyshev_dis"].apply(lambda x: pred_idx(x))



    return train
    

In [67]:
predicted = predictions(train)

cosine start


In [85]:
predicted

context  \
0     Architecturally, the school has a Catholic cha...   
1     Architecturally, the school has a Catholic cha...   
2     Architecturally, the school has a Catholic cha...   
3     Architecturally, the school has a Catholic cha...   
4     Architecturally, the school has a Catholic cha...   
5     As at most other universities, Notre Dame's st...   
6     As at most other universities, Notre Dame's st...   
7     As at most other universities, Notre Dame's st...   
8     As at most other universities, Notre Dame's st...   
9     As at most other universities, Notre Dame's st...   
10    The university is the major seat of the Congre...   
11    The university is the major seat of the Congre...   
12    The university is the major seat of the Congre...   
13    The university is the major seat of the Congre...   
14    The university is the major seat of the Congre...   
15    The College of Engineering was established in ...   
16    The College of Engineering was established in ...   
17    The College of Engineering was established in ...   
18    The College of Engineering was established in ...   
19    The College of Engineering was established in ...   
20    All of Notre Dame's undergraduate students are...   
21    All of Notre Dame's undergraduate students are...   
22    All of Notre Dame's undergraduate students are...   
23    All of Notre Dame's undergraduate students are...   
24    The university first offered graduate degrees,...   
25    The university first offered graduate degrees,...   
26    The university first offered graduate degrees,...   
27    The university first offered graduate degrees,...   
28    The university first offered graduate degrees,...   
29    The Joan B. Kroc Institute for International P...   
...                                                 ...   
1284  On 12 July 2007, European Court of Human Right...   
1285  About 30 people have been indicted for partici...   
1286  About 30 people have been indicted for partici...   
1287  About 30 people have been indicted for partici...   
1288  About 30 people have been indicted for partici...   
1289  About 30 people have been indicted for partici...   
1290  Slobodan Milošević, as the former President of...   
1291  Slobodan Milošević, as the former President of...   
1292  Slobodan Milošević, as the former President of...   
1293  Slobodan Milošević, as the former President of...   
1294  Slobodan Milošević, as the former President of...   
1295  The International Criminal Tribunal for Rwanda...   
1296  The International Criminal Tribunal for Rwanda...   
1297  The International Criminal Tribunal for Rwanda...   
1298  The International Criminal Tribunal for Rwanda...   
1299  The International Criminal Tribunal for Rwanda...   
1300  There has been much debate over categorizing t...   
1301  There has been much debate over categorizing t...   
1302  There has been much debate over categorizing t...   
1303  There has been much debate over categorizing t...   
1304  There has been much debate over categorizing t...   
1305  In March 2005, the Security Council formally r...   
1306  In March 2005, the Security Council formally r...   
1307  In March 2005, the Security Council formally r...   
1308  In March 2005, the Security Council formally r...   
1309  Other authors have focused on the structural c...   
1310  Other authors have focused on the structural c...   
1311  Other authors have focused on the structural c...   
1312  Other authors have focused on the structural c...   
1313  Other authors have focused on the structural c...   

                                               question  answer_start  \
0     To whom did the Virgin Mary allegedly appear i...           515   
1     What is in front of the Notre Dame Main Building?           188   
2     The Basilica of the Sacred heart at Notre Dame...           279   
3                     What is the Grotto at Notre Dame?           381   
4     What sits on top o

## Accuracy

In [69]:
def accuracy(target, predicted):
    
    acc = (target==predicted).sum()/len(target)
    
    return acc

### Accuracy for  euclidean Distance

In [84]:
print(accuracy(predicted["target"], predicted["pred_idx_euc"]))

0.2929984779299848


### Accuracy for Cosine Similarity and others

In [83]:
print(accuracy(predicted["target"], predicted["pred_idx_cos"]))

0.24885844748858446


In [72]:
print(accuracy(predicted["target"], predicted["pred_idx_min"]))

0.3036529680365297


In [73]:
print(accuracy(predicted["target"], predicted["pred_idx_che"]))

0.24733637747336376


In [57]:
# predicted.to_csv("train_detect_sent.csv", index=None)